### ISSUE TITLE
ImportError: cannot import name 'monitoring' from 'jax' ??

### ISSUE THREAD

**Issue by chenqq1** [janEbert/PyTorch-VeLO#1]
I used jax==0.3.25+cuda11.cudnn82, jaxlib==0.3.25+cuda11.cudnn82, flax==0.6.4, chex==0.1.5, torch==1.10.0, but it comes out "ImportError: cannot import name 'monitoring' from 'jax'".

**Comment by janEbert** [comment]
Thanks for the report and sorry for the problem. The requirements specified in [`learned_optimization`](https://github.com/google/learned_optimization) are sadly not strict enough. You could try the latest JAX (i.e. 0.4.5), that should work.

**Comment by janEbert** [comment]
Feel free to re-open if you were still encountering issues!
